source 'http://rubygems.org'

gem 'rails', '3.0.1'

gem 'mongoid',      :git => 'git://github.com/mongoid/mongoid.git'
gem 'bson_ext', '>=1.0'
gem 'mechanize'
gem 'grackle'
gem 'omniauth'

gem 'ruby-debug19'

# gem 'twitter_oauth'
